import logging
import json
from typing import Dict, Any

logger = logging.getLogger("CIBridge")

class CIBridge:
    """Bridge for integrating the QA organization with CI/CD tools (GitHub Actions, Jenkins, etc)."""
    
    @staticmethod
    def format_for_github(report: str, evaluation: Dict[str, Any]) -> str:
        """Formats the final summary and evaluation for a GitHub PR comment."""
        status_emoji = "✅" if evaluation.get("score", 0) >= 7 else "⚠️"
        github_comment = f"""
### {status_emoji} Agentic QA Mission Summary

**Score:** {evaluation.get('score', 0)}/10
**Rationale:** {evaluation.get('rationale', 'No rationale provided.')}

{report}

---
*Generated by Antigravity QA Organization*
"""
        return github_comment

    @staticmethod
    def check_gate(evaluation: Dict[str, Any], threshold: int = 7) -> bool:
        """Determines if the mission passed the quality gate."""
        return evaluation.get("score", 0) >= threshold
