from typing import TypedDict, List, Annotated
import operator
from .qa_lead_agent import TestMission

class QAOrganizationState(TypedDict):
    """The shared state for the agentic QA organization."""
    # The initial input from the user (feature request, PR, etc.)
    input: str
    
    # The mission plan generated by the Lead Agent
    mission: TestMission
    
    # A list of findings/reports from specialist agents
    reports: Annotated[List[str], operator.add]
    
    # The current task being worked on
    current_task: str
    
    # Final summary report
    final_report: str
