from typing import TypedDict, List, Annotated, Optional
import operator
from ..agents.qa_lead_agent import TestMission

class QAOrganizationState(TypedDict):
    """The shared state for the agentic QA organization."""
    # The initial input from the user (feature request, PR, etc.)
    input: str
    
    # The mission plan generated by the Lead Agent
    mission: TestMission
    
    # A list of findings/reports from specialist agents
    reports: Annotated[List[str], operator.add]
    
    # The current task being worked on
    current_task: str
    
    # Track visited agents to support multi-agent missions
    visited_agents: Annotated[List[str], operator.add]
    
    # Final summary report
    final_report: str
    
    # Manual agent selection override
    manual_agents: Optional[List[str]]
